"""tambah last_inbox_read_time

Revision ID: 6a3c15b2d9dc
Revises: 4204ad7e7fb8
Create Date: 2018-07-24 15:24:01.229121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3c15b2d9dc'
down_revision = '4204ad7e7fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_inbox_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_inbox_read_time')
    # ### end Alembic commands ###
